services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    WiPhi\DieLosungen\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,WiPhiDieLosungenBundle.php}
        public: true